//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAppGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoAppGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8673524_ic_fluent_person_note_filled_icon {
            get {
                object obj = ResourceManager.GetObject("8673524_ic_fluent_person_note_filled_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_pastel_background {
            get {
                object obj = ResourceManager.GetObject("blue-pastel-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__10_ {
            get {
                object obj = ResourceManager.GetObject("download (10)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__11_ {
            get {
                object obj = ResourceManager.GetObject("download (11)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__12_ {
            get {
                object obj = ResourceManager.GetObject("download (12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__13_ {
            get {
                object obj = ResourceManager.GetObject("download (13)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__9_ {
            get {
                object obj = ResourceManager.GetObject("download (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__9_1 {
            get {
                object obj = ResourceManager.GetObject("download (9)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hehe {
            get {
                object obj = ResourceManager.GetObject("hehe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hihi {
            get {
                object obj = ResourceManager.GetObject("hihi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap huhu {
            get {
                object obj = ResourceManager.GetObject("huhu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_100 {
            get {
                object obj = ResourceManager.GetObject("icons8-add-100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_coffee_shop_50__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-coffee-shop-50 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_coffee_shop_50__3_ {
            get {
                object obj = ResourceManager.GetObject("icons8-coffee-shop-50 (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_coffee_shop_64__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-coffee-shop-64 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_coffee_to_go_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-coffee-to-go-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_delete_100 {
            get {
                object obj = ResourceManager.GetObject("icons8-delete-100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê1 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê2 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê3 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê4 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê5 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê6 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê7 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Màu_đào_và_Nâu_Phông_chữ_Hình_vẽ_một_nét_Đơn_giản_Sản_phẩm_Cà_phê_Biểu_trưng_Cà_phê8 {
            get {
                object obj = ResourceManager.GetObject("Màu đào và Nâu Phông chữ Hình vẽ một nét Đơn giản Sản phẩm Cà phê Biểu trưng Cà p" +
                        "hê8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snapedit_1744729966755 {
            get {
                object obj = ResourceManager.GetObject("snapedit_1744729966755", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z6423047769427_98572fec2ce9451c90f45755a6fedb62 {
            get {
                object obj = ResourceManager.GetObject("z6423047769427_98572fec2ce9451c90f45755a6fedb62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z6423047769427_98572fec2ce9451c90f45755a6fedb621 {
            get {
                object obj = ResourceManager.GetObject("z6423047769427_98572fec2ce9451c90f45755a6fedb621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z6423047769427_98572fec2ce9451c90f45755a6fedb622 {
            get {
                object obj = ResourceManager.GetObject("z6423047769427_98572fec2ce9451c90f45755a6fedb622", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z6423047769427_98572fec2ce9451c90f45755a6fedb623 {
            get {
                object obj = ResourceManager.GetObject("z6423047769427_98572fec2ce9451c90f45755a6fedb623", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
